const COUNTRY_TO_FLAG_CODE: Record<string, string> = {
  algeria: "dz",
  argentina: "ar",
  australia: "au",
  austria: "at",
  belgium: "be",
  "bosnia-herzegovina": "ba",
  brazil: "br",
  cameroon: "cm",
  canada: "ca",
  "cape verde islands": "cv",
  "cape verde": "cv",
  chile: "cl",
  colombia: "co",
  "congo dr": "cd",
  "costa rica": "cr",
  croatia: "hr",
  curaçao: "cw",
  curacao: "cw",
  czechia: "cz",
  denmark: "dk",
  ecuador: "ec",
  egypt: "eg",
  england: "gb-eng",
  france: "fr",
  germany: "de",
  ghana: "gh",
  haiti: "ht",
  honduras: "hn",
  iceland: "is",
  iran: "ir",
  "ir iran": "ir",
  iraq: "iq",
  "ivory coast": "ci",
  jamaica: "jm",
  japan: "jp",
  jordan: "jo",
  "south korea": "kr",
  "korea republic": "kr",
  mexico: "mx",
  morocco: "ma",
  netherlands: "nl",
  "new zealand": "nz",
  nigeria: "ng",
  "northern ireland": "gb-nir",
  norway: "no",
  panama: "pa",
  paraguay: "py",
  peru: "pe",
  poland: "pl",
  portugal: "pt",
  qatar: "qa",
  "saudi arabia": "sa",
  scotland: "gb-sct",
  senegal: "sn",
  serbia: "rs",
  "south africa": "za",
  spain: "es",
  suriname: "sr",
  sweden: "se",
  switzerland: "ch",
  tunisia: "tn",
  turkey: "tr",
  ukraine: "ua",
  "united states": "us",
  usa: "us",
  uruguay: "uy",
  uzbekistan: "uz",
  wales: "gb-wls",
  venezuela: "ve",
};

export function getFlagCode(teamName: string | null | undefined): string | null {
  if (!teamName) return null;
  return COUNTRY_TO_FLAG_CODE[teamName.trim().toLowerCase()] ?? null;
}

export function getFlagUrl(teamName: string | null | undefined): string | null {
  const code = getFlagCode(teamName);
  return code ? `https://flagcdn.com/${code}.svg` : null;
}
